#!/bin/bash
# Renderダッシュボードでの手動設定用スクリプト

echo "=== Web版Claude連携のための環境変数設定ガイド ==="
echo "このスクリプトは、Renderダッシュボードで設定すべき環境変数の一覧を表示します。"
echo "以下の手順で設定してください："
echo ""
echo "1. Renderダッシュボード（https://dashboard.render.com/）にログイン"
echo "2. サービス「srv-d0g9goq4d50c73fk10d0」を選択"
echo "3. 「Environment」タブを選択"
echo "4. 以下の環境変数を設定："
echo ""
echo "NODE_ENV=production"
echo "CORS_ORIGIN=https://claude.ai,https://*.claude.ai,https://api.anthropic.com,https://claude.anthropic.com"
echo "ENABLE_WEB_CLAUDE_COMPAT=true"
echo "ALLOWED_REDIRECT_URIS=https://claude.ai/oauth/callback,https://api.anthropic.com/oauth/callback,https://claude.anthropic.com/oauth/callback"
echo ""
echo "5. 「Save Changes」ボタンをクリック"
echo "6. 「Manual Deploy」ボタンをクリック"
echo "7. オプションで「Clear build cache & deploy」を選択してクリーンビルド"
echo ""
echo "=== 設定完了後 ==="
echo "デプロイが完了したら、以下のURLにアクセスして動作確認を行ってください："
echo "https://render-mcp-server.onrender.com/"
echo "https://render-mcp-server.onrender.com/auth/status"
echo "https://render-mcp-server.onrender.com/oauth/status"
echo ""
echo "=== Web版Claudeとの連携方法 ==="
echo "デプロイ完了後、Web版Claudeの設定画面で以下のURLを設定してください："
echo "https://render-mcp-server.onrender.com"
echo ""
echo "設定が完了したら、環境変数の設定とデプロイ成功をリモートMCPサーバー実装報告書に記録してください。"