services:
  - type: web
    name: remote-mcp-server
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5678
      - key: LOG_LEVEL
        value: info
    regions:
      - oregon
    numInstances: 1
